### ISSUE TITLE
get doc site running under node-swig

### ISSUE THREAD

**Issue by cdaringe** [node-swig/swig-templates#8]

**Comment by Lochlan** [comment]
I made a node-swig.github.io repo (see here: http://node-swig.github.io/), we definitely have gh pages working.  I think we just need to push to the gh-pages branch for this to work.

I tried running the `make gh-pages` target on my box and it errored out with

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'swig'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.exports.swig (/Users/lochlan/Documents/dev/swig/node_modules/still/node_modules/consolidate/lib/consolidate.js:123:50)
    at /Users/lochlan/Documents/dev/swig/node_modules/still/lib/build.js:42:24
    at /Users/lochlan/Documents/dev/swig/node_modules/still/lib/data.js:50:9
    at /Users/lochlan/Documents/dev/swig/node_modules/still/lib/data.js:29:5
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

The offending line in the `gh-pages` target recipe is

```
node_modules/.bin/still docs -o tmp -i "layout" -i "json" -i "less" -v
```

I'm pretty sure we could just edit a file on the gh-pages branch, or something like that, although we should figure out why `make gh-pages` isn't working.

As an aside, I'm not that into the way the gh-pages branch works here, I don't like the heavy build process.

**Comment by Lochlan** [comment]
So I was hacking around in the makefile and I managed to get the docs site up, which worked as soon as I pushed to the gh-pages branch: http://node-swig.github.io/swig/

I have not yet gotten `node_modules/.bin/still docs -o 'tmp' -i "layout" -i "json" -i "less" -v` working.  If I install this [still project](https://github.com/paularmstrong/still) globally I am able to run `still docs -o 'tmp' -i "layout" -i "json" -i "less" -v` successfully.  I will dive a little deeper and see if I can't figure out why this `consolidate` call is failing

**Comment by Lochlan** [comment]
This is some kind of circular dependency issue.  I'm not necessarily a super node expert and I'm unfamiliar with this class of problem in node, but the issue seems to be that node_modules/still/node_modules/swig does not exist.  If I rectify that issue then the makefile recipes seem to work.

I'm not sure what the actual fix is here—@cdaringe or @paulcpederson do either of you know?

**Comment by paulcpederson** [comment]
@Lochlan global install of still will work, but I don't think that's the answer as that would force all contributors to install it globally. Could have problems with different versions, etc.

Since npm `2.0.0` you can just specify [Local Paths](https://docs.npmjs.com/files/package.json#local-paths) for modules. I just tried this locally and it worked great. Basically in `devDependencies`  you just add:

```
"devDependencies": {
  "swig": "./"
}
```

That way still will find a module called swig that is just whatever is in the folder.

**Comment by cdaringe** [comment]
i think as @paulcpederson suggests is fine for now.  looks like `still` uses `consolidate`, which eventually tries to require in the specified `engine`.  perhaps we can also add a `postpublish` hook to auto-build those docs everytime we bump version.

**Comment by paulcpederson** [comment]
@cdaringe I think we could set it up so that successfull travis builds on `master` build the docs using a travis [script provider](https://docs.travis-ci.com/user/deployment/script/).

**Comment by prakaashkpk** [comment]
Guys, consider this as workaround until you make the documentation available from node-swig. 
I have made changes manually in all index files to make the documentation come online here https://prakaashkpk.github.io/swig-docs/ 

I have been trying to compile the entire project myself and not yet succeeded. 

Thanks for taking initiative to make this project come alive again. Will be happy to contribute to this project in my spare time.

**Comment by nedkelly** [comment]
Where is this project at right now? I've just invested the past 3 month's building a swig based project with an indefinite life expectancy so I'm more than happy to contribute where I can. That said I'm running it on gulp-swig so it would be good to see that project updated to use swig-templates if this is indeed the most likely predecessor to the original project.

One way or another this engine needs to be preserved because nothing else I've tried to date comes close to what's on offer here.

**Comment by cdaringe** [comment]
All targetted and issue associated PRs welcome!  No one is full time on this lib, but there are people watching it and caring about its critical parts.  Even if maintenance is sparse, swig-templates is very stable.

**Comment by Lochlan** [comment]
@nedkelly it looks like https://github.com/colynb/gulp-swig is pretty stale itself.  I would suggest opening a PR on that project to point to our package, and if it doesn't land I would suggest forking gulp-swig.

**Comment by paulcpederson** [comment]
I have the doc site running locally, but am unable to commit because `npm ls` is exiting with an error :/ 

It's actually pretty interesting how it works currently, essentially it's set up to use the `jsdoc` command to output to stdin and redirecting that into a json file. That JSON file is what still uses to generate the site. 

If we moved to another static site generator we could basically just point it at the same json file and keep the existing doc template and indiana jones it. 

I'll try a bit more, but we may need to generate the docs with something else.

**Comment by Lochlan** [comment]
Your conclusion mirrors mine but I was thinking that the lift to get to a
new site generator might be too heavy for the short term goal of getting
docs working.  If you see a good (read: easy) path forward, though, I say
go for it.  Always down to hack on this after work, too, if you want to
stop by or meet up somewhere downtown.

**Comment by Lochlan** [comment]
I got the docs site running by changing the repo name to "swig" as that was what was being pointed at.  Take a look here: http://node-swig.github.io/swig/

I hope you guys don't mind that I went ahead and did that for the sake of getting docs working.  I personally prefer the repo name being "swig" anyway, even if the package is now called "swig-templates".

@paulcpederson I [fixed the VERSION assignment in the makefile](https://github.com/node-swig/swig/commit/bbf788b5bdafda33bbaf9ae46635fc5901a4b87f) which I think might have been your "`npm ls`" issue?  I have a handle on how to build and run the docs generator and push to the gh-pages branch although not in a good way, I'm doing some weird hacky setup things locally.

Working on updating the docs now.

**Comment by Lochlan** [comment]
I had a change of heart about whether or not renaming the repo was a reasonable idea.  Got the relevant `baseurl` assignments fixed so now we're back to "swig-templates" with working docs!  :tada:

**Comment by paulcpederson** [comment]
@Lochlan what "weird hacky setup" things are you doing locally?

**Comment by Lochlan** [comment]
@paulcpederson I didn't really understand the [comment you made about local paths](https://github.com/node-swig/swig-templates/issues/8#issuecomment-188334861) (perhaps you can explain in greater/more explicit detail what steps you go through to make line 169 in the makefile succeed?), I still have [the same "Cannot find module 'swig'" issue I mentioned earlier](https://github.com/node-swig/swig-templates/issues/8#issuecomment-187996838).  To combat it I installed still globally (as I previously mentioned) and changed line 169 to this:

```
@still docs -o ${TMP} -i "layout" -i "json" -i "less" -v
```

But then the rest of the `gh-pages` makefile recipe fails because of uncommitted changes in my working tree (the Makefile itself), so I have to add the following line right after:

```
git reset --hard head
```
thus undoing the changes to the makefile I just made.  This is obviously a super weird approach.  Basically if you can explain how to ensure that still knows where to find swig then we can have a repeatable way of updating docs.

**Comment by paulcpederson** [comment]
ok, I had the local thing working back when I wrote that, but I tried it this week and now it doesn't work. (Maybe because I upgraded node?)

In any case, you got docs up on the internet, which are now the only docs for swig, so that is a huge victory. 

I'm working on an experimental branch where I'm just ripping out still entirely so I'll let you know how that goes.

**Comment by Lochlan** [comment]
Marking this issue as closed as docs are now functional

**Comment by paulcpederson** [comment]
make thinks my coverage is 0% so I can't commit at all...

**Comment by Lochlan** [comment]
@paulcpederson `git commit --no-verify` to get through the git hooks, assuming that's what you're talking about.

You can also get around the git hooks if you don't [install them](https://github.com/node-swig/swig-templates/blob/9bae4831a445aebc051187d6a58b9c8a453e65e2/Makefile#L16) when setting up.

I hate the git hooks, they're heavy handed and really don't do much that CI can't do.

**Comment by paulcpederson** [comment]
@Lochlan you're a hero.
